version: '3.3'

services:
  bot:
    container_name: monopoly_telegram_bot
    stop_signal: SIGINT
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/home/Telegram_bot
    command: python3 main.py
